apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: sample-kube-resources-subscription
spec:
  channel: kuberesources/sample-kube-resources-github
  placement:
    local: false
  packageFilter:
    filterRef:
      name: resource-filter-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-filter-configmap
data:
    path: examples/github-channel